version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/js"
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
      prettier:
        patterns:
          - "prettier"
          - "@trivago/prettier-plugin-sort-imports"
          - "prettier-plugin-*"
      typescript:
        patterns:
          - "typescript"
          - "ts-*"
          - "@types/node"
      husky:
        patterns:
          - "husky"
          - "@commitlint/*"
          - "is-ci"
      vite:
        patterns:
          - "vite"
          - "vite-plugin-*"
          - "@vitejs/*"
      electron-forge:
        patterns:
          - "@electron-forge/*"
          - "@electron/*"
          - "electron"
          - "electron-squirrel-startup"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@electron/fuses"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
