/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as WhatsNewRouteImport } from './routes/whats-new';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as OnboardingRouteImport } from './routes/onboarding';
import { Route as IndexRouteImport } from './routes/index';

const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/onboarding': typeof OnboardingRoute;
  '/settings': typeof SettingsRoute;
  '/whats-new': typeof WhatsNewRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/onboarding': typeof OnboardingRoute;
  '/settings': typeof SettingsRoute;
  '/whats-new': typeof WhatsNewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/onboarding': typeof OnboardingRoute;
  '/settings': typeof SettingsRoute;
  '/whats-new': typeof WhatsNewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/onboarding' | '/settings' | '/whats-new';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/onboarding' | '/settings' | '/whats-new';
  id: '__root__' | '/' | '/onboarding' | '/settings' | '/whats-new';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  OnboardingRoute: typeof OnboardingRoute;
  SettingsRoute: typeof SettingsRoute;
  WhatsNewRoute: typeof WhatsNewRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-new': {
      id: '/whats-new';
      path: '/whats-new';
      fullPath: '/whats-new';
      preLoaderRoute: typeof WhatsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding': {
      id: '/onboarding';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  WhatsNewRoute: WhatsNewRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
