/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as StatsRouteImport } from './routes/stats';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ReplaysRouteImport } from './routes/replays';
import { Route as IndexRouteImport } from './routes/index';

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const ReplaysRoute = ReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/replays': typeof ReplaysRoute;
  '/settings': typeof SettingsRoute;
  '/stats': typeof StatsRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/replays': typeof ReplaysRoute;
  '/settings': typeof SettingsRoute;
  '/stats': typeof StatsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/replays': typeof ReplaysRoute;
  '/settings': typeof SettingsRoute;
  '/stats': typeof StatsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/replays' | '/settings' | '/stats';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/replays' | '/settings' | '/stats';
  id: '__root__' | '/' | '/replays' | '/settings' | '/stats';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ReplaysRoute: typeof ReplaysRoute;
  SettingsRoute: typeof SettingsRoute;
  StatsRoute: typeof StatsRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats';
      path: '/stats';
      fullPath: '/stats';
      preLoaderRoute: typeof StatsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/replays': {
      id: '/replays';
      path: '/replays';
      fullPath: '/replays';
      preLoaderRoute: typeof ReplaysRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReplaysRoute: ReplaysRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
